// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCTW6D7KM-VKZfNo7sfyjeH6-xmA4wD8',
    appId: '1:86977734978:web:0acd70d99255d8e00000db',
    messagingSenderId: '86977734978',
    projectId: 'device-streaming-158247e9',
    authDomain: 'device-streaming-158247e9.firebaseapp.com',
    storageBucket: 'device-streaming-158247e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKMWHjCT6xLFUz35BI5_1_FwX2J_B_TE',
    appId: '1:86977734978:android:68387e43b9d892190000db',
    messagingSenderId: '86977734978',
    projectId: 'device-streaming-158247e9',
    storageBucket: 'device-streaming-158247e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSE5YSqSuyh5rn0ZKo8CkQWWeu4AbhOY',
    appId: '1:86977734978:ios:4eb8429ff05bc8e50000db',
    messagingSenderId: '86977734978',
    projectId: 'device-streaming-158247e9',
    storageBucket: 'device-streaming-158247e9.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthHomeKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSE5YSqSuyh5rn0ZKo8CkQWWeu4AbhOY',
    appId: '1:86977734978:ios:4eb8429ff05bc8e50000db',
    messagingSenderId: '86977734978',
    projectId: 'device-streaming-158247e9',
    storageBucket: 'device-streaming-158247e9.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthHomeKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxCTW6D7KM-VKZfNo7sfyjeH6-xmA4wD8',
    appId: '1:86977734978:web:294e616d256dc1cc0000db',
    messagingSenderId: '86977734978',
    projectId: 'device-streaming-158247e9',
    authDomain: 'device-streaming-158247e9.firebaseapp.com',
    storageBucket: 'device-streaming-158247e9.firebasestorage.app',
  );
}
